### ISSUE TITLE
Yeni post oluşturmak için gerekli sayfanın hazırlanması

### ISSUE THREAD

**Issue by mucahitnezir** [mikail-aydin/vuejs-starter#2]
- [x] ``http://localhost:3000/posts/new`` route adresine sahip yeni bir sayfa oluşturulacak.
- [x] Sayfada bir form, formun altında 3 input ve bir submit butonu olacak. (input alanları: ``title``, ``body``, ``userId``)
- [x] Form submit methodunda ``https://jsonplaceholder.typicode.com/posts`` adresine ``axios`` ile ``post`` isteği gönderilecek. Form verileri dahil edilecek. (Örnek kullanım: ``axios.post('/posts', this.formData)``)

<img width="253" alt="Screen Shot 2022-07-13 at 19 33 18" src="https://user-images.githubusercontent.com/9297972/178785103-ed362e17-c615-449d-a6eb-675d06a8f76c.png">
<img width="385" alt="Screen Shot 2022-07-13 at 19 34 30" src="https://user-images.githubusercontent.com/9297972/178785325-094c3d66-ad83-44eb-9537-56018fc15b67.png">

**Comment by mikail-aydin** [comment]
Tamamlandı @mucahitnezir
